### ISSUE TITLE
Not working on chrome

### ISSUE THREAD

**Issue by jk-1** [openmole/scaladget#9]
Nice work!! 
I just checked your demo: http://zebulon.iscpif.fr/~leclaire/scaladget/
Unfortunately at least following scaladgets are not working correctly on chrome Version 57.0.2987.133 (64-bit) on Ubuntu:
- modal dialog: nohting opens
- tabs: My Second is selected by default. You cannot select My First, nothing happens when you click My First, when you click My Second browser window scrolls so that Your name is on the top of the window.
- tooltips: No tooltips are visible.

All these work OK when tested on Firefox 52.0.2 on Ubuntu

**Comment by mathieuleclaire** [comment]
Hi,
try to desactivate your adblock on the page and refresh the page. I have the same issue when it is activated on chrome.

**Comment by jk-1** [comment]
Thanks for the tip. I do not have adblock plugin. I disabled all my plugins and demo started to work. However when I enabled one of these at a time: LastPass, X Marks Bookmark Sync, Google Docs the demo did not work correctly. I enabled one, checked demo, disabled all, checked demo, enabled next, checked demo...

**Comment by mathieuleclaire** [comment]
I will have a look in detail. It is no supposed to happen. Thanks for reporting.

**Comment by mathieuleclaire** [comment]
Actually, the tabs was buggy. It was not related to the adblock. Actually, I generate a random ID for the tabs, and it does not have to start with a digit but with a character. I guess, the inferred type in js should differ... So happy to generate the js :) ! The fix: d869d6ed89e90ae75ef195774ae2d6b6895ba925. The [demo](http://zebulon.iscpif.fr/~leclaire/scaladget/) has been updated

**Comment by jk-1** [comment]
Hi
Thanks for the fix. Now modal opens and tooltips are visible also when plugins enabled. Tabs work just like in my first message described. Actually they do not work  when plugins enabled or disabled and they do not work when using firefox and plugins enabled? (This was working earlier today)

**Comment by mathieuleclaire** [comment]
Everything is working fine for me. Did you make a Ctrl + F5 to trash the cache ?

**Comment by jk-1** [comment]
That helped. Now everything works also on chrome with plugins enabled. Thanks for the fast fix!

**Comment by mathieuleclaire** [comment]
Nice, enjoy !
